sonar.projectKey=Rudresh77_Demo2
sonar.organization=rudresh77


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Demo2
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# sonar.sources=src
sonar.exclusions=**/*.html,node_modules
sonar.sources=src,public


# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
# Tell SonarCloud to ignore these files ONLY for coverage calculations
sonar.coverage.exclusions=src/routes.js, src/server.js, src/db.js